### ISSUE TITLE
Use NAICS Browser to give more information on NAICS-relevant data products

### ISSUE THREAD

**Issue by ljwolf** [ljwolf/cenpy#12]
http://naics.codeforamerica.org/

**Comment by geoffrey-eisenbarth** [comment]
Is the premise behind this issue to replace references to the local file stfipstable.csv?

Also, do you know how reliable the Code for America reference is? In my work projects, I'm pulling NAICS data from (I think) the BEA, but I'm pretty sure it doesn't have industry description texts, which is something I'm looking for. Haven't dug into the Code For America source, so it might be best to reference what they're referencing if it's decided that the linked project isn't reliable. 

Just a thought; I want to contribute in ways that I can, also considering trying to create a package that's similar to this for the BEA API, and I'm learning a lot about how to set things up though my involvement here.

**Comment by ljwolf** [comment]
Nope, I was thinking of this as something to grab for metadata, giving people better descriptions for the variables & columns than that which is provided directly from the endpoint. 

And, that'd be neat! I was thinking about trying to unify efforts underneath [pandas-datareader](https://pandas-datareader.readthedocs.io/en/latest/), adding cenpy as a sub-package, or storing the specific "cleaner" interfaces as `acs` or `decennial2010` as endpoints in there relying on cenpy. 

Haven't had the time to do that, though...

**Comment by geoffrey-eisenbarth** [comment]
Ah, gotcha! I hadn't heard of ``pandas-datareader``, sounds interesting though. Thanks for pointing it out!

**Comment by ljwolf** [comment]
This is enhanced by #27 and #28, but It'd still be nice if we could get more metadata on the available entries & columns. I still usually need to pull up the official documentation when working in jupyterlab.

**Comment by dfolch** [comment]
Would it be possible to add a link to the Social Explorer page? There is a page for each table and variable, and the URLs are pretty clean. Social Explorer doesn’t have all the datasets, it probably has the most popular ones. 

- CBP: https://www.socialexplorer.com/data/CBP2014/metadata/?ds=ORG&var=CBP2014_032_EMP_260_115
- ACS: https://www.socialexplorer.com/data/ACS2016_5yr/metadata/?ds=ACS16_5yr&var=B01001G007

**Comment by ljwolf** [comment]
I've pulled the ideas from here into their own issues, and will close this since I do not want to use naicsbrowser directly in the next iteration of the product API.

**Comment by dfolch** [comment]
I've been looking for a place to put an example for pulling County Business Patterns data by NAICS code. I'll just drop it here in case this ticket comes up in  a Google search.

A few challenges:
- The NAICS code attribute changes every five years; so for 2000 data it's `NAICS1997` and for 2008 data it's `NAICS2007`.
- I could not figure out how to pull multiple NAICS codes in one query. This may be because the data comes in a "long" format. Could do something like stacking multiple queries and then doing a `pivot` to get the data into a hierarchical "wide" dataframe.

```python
import cenpy as cen  # example is using cenpy version 1.0.0dev

cols = ['ESTAB','EMP']

### CBP 2000
api_conn = cen.products.APIConnection('CBP2000')

# Get one NAICS code's establishment and employment counts for all counties in a state
data1 = api_conn.query(cols=cols, geo_unit='county', geo_filter={'state':'04'}, NAICS1997='11')

### CBP 2008
api_conn = cen.products.APIConnection('CBP2008')

# Get total establishment and employment counts for all counties in a state
data2 = api_conn.query(cols=cols, geo_unit='county', geo_filter={'state':'04'})

# Get one NAICS code's establishment and employment counts for all counties in a state
data3 = api_conn.query(cols=cols, geo_unit='county', geo_filter={'state':'04'}, NAICS2007='11')

# Get all NAICS codes' establishment and employment counts for one state
cols_more = cols + ['NAICS2007']
data4 = api_conn.query(cols=cols_more, geo_unit='state:04')

# Get all NAICS codes' establishment and employment counts for all counties in a state
# This returns the following error: HTTPError: 400 error: estimated query results exceed cell limit of 1431332
data5 = api_conn.query(cols=cols_more, geo_unit='county', geo_filter={'state':'04'})
```
