### ISSUE TITLE
Work correctly with projections

### ISSUE THREAD

**Issue by ljwolf** [ljwolf/cenpy#15]
Right now, I'm just [throwing the `spatialReference` component of the API response into the crs dict and expecting it to know what's up.](https://github.com/ljwolf/cenpy/blob/master/cenpy/tiger.py#L184) Unfortunately, `fiona` doesn't know what's up, since that's a nonstandard format for whatever is doing the projections under the hood. 

Instead, I think it may be more proper to:
```python
wkid = datadict['spatialReference'].get('wkid', None)
if wkid is not None:
    outdf.crs = {'init':'wkid:{}'.format(int(wkid))}
```
or something I need to figure out.

**Comment by dfolch** [comment]
If I understand the ticket, here is my workaround for the moment:
```{python}
api_conn.set_mapservice('tigerWMS_ACS2015')
geodata = api_conn.mapservice.query(layer=8, where='STATE=12 and COUNTY=073', pkg='geopandas')
geodata.crs = {'init' :'epsg:3857'}  # this corrects weird error when saving as shp
```

**Comment by ljwolf** [comment]
yep, that should work when the data is in epsg 3857. To make it work arbitrarily, we'd need to [parse `spatialReference` from the ESRI api into an epsg code](https://github.com/ljwolf/cenpy/blob/master/cenpy/tiger.py#L184). Just haven't had the time to do that yet.

**Comment by ljwolf** [comment]
A tentative fix is [here](https://github.com/ljwolf/cenpy/commit/d1422917389a0d563ac4698030b4caac980d6285). I'm not sure the extent to which it's ok to assume that `latestWkid` is always an epsg code, but I think most census geographies are provided in EPSG 3857, and this is given by the `latestWkid` part of the `spatialReference` field.
