### ISSUE TITLE
Why doesn't cenpy access ACSSF5Y2016?

### ISSUE THREAD

**Issue by sashigurram** [ljwolf/cenpy#17]
Why does 

```
dataset = 'ACSSF5Y2016'
cen.explorer.explain(dataset)
```

result in 

> Traceback (most recent call last):
>   File "C:/Users/sgurram/PycharmProjects/demographics_tables/read_censusdata_cenpy.py", line 6, in <module>
>     con = cen.base.Connection(dataset)
>   File "C:\Users\sgurram\PycharmProjects\venv\Lib\site-packages\cenpy\remote.py", line 28, in __init__
>     curr = exp.APIs[api_name]
> KeyError: 'ACSSF5Y2016'

**Comment by ljwolf** [comment]
The census bureau probably changed the keys. 

`cenpy.explorer.available(verbose=True)`

will tell you what the currently existing keys & descriptions for all the census products are.

**Comment by sashigurram** [comment]
Thanks. I think the 2016 ACS 5 year summaries are not yet available via API.

BTW, do you know if there is a way to download the data for all the block groups in the nation in one go? I am trying the following but it results in a invalid geography hierarchy

```
g_unit = 'block group:*'
g_filter = {'state':'*', 'county':'*'}
cols = con.varslike('B00001_001E')
cols.extend(['NAME', 'BLKGRP'])
data = con.query(cols, geo_unit=g_unit, geo_filter=g_filter)
print(data)
```

> raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.census.gov/data/2015/acs5?get=B00001_001E,NAME,BLKGRP&for=block+group:*&in=state:*+county:*
>

**Comment by ljwolf** [comment]
Yeah, I don't see what I'd expect to be it, either.... usually I'd think it'd look something like `ACSSF5Y2011` if it's in there. 

The census's `API`, so far as I understand it, requires fully-specified geo-in-geo queries, so these will crawl the hierarchy by making many repeated requests. You may get rate limited if you don't have an API key. For now, you should be able to do that using the `cenpy.tools.national_to_blockgroup` tool. 

I've intended to make this easier to use by focusing on specific data products and just hardcoding search paths, like `tidycensus`. But, `cenpy`'s original design was for a crawler for a startup to avoid repeated polling of the Census API, so I did not build those.
