### ISSUE TITLE
ImportError: cannot import name JSONDecodeError

### ISSUE THREAD

**Issue by ndilekli** [ljwolf/cenpy#19]
When the library (cenpy) is imported, I get the following error:

ImportError: cannot import name JSONDecodeError

I use Python 2.7. What might be causing this issue?

Thanks

**Comment by ljwolf** [comment]
This is a duplicate of #13. The error is caused because the package is not available in Python 2. I'm sorry; I need to mark it as python 3-only and cut a new release.

**Comment by ndilekli** [comment]
Thanks, yeah, that's what I already figured!
