### ISSUE TITLE
Default value of geo_unit in Connection.query()

### ISSUE THREAD

**Issue by geoffrey-eisenbarth** [ljwolf/cenpy#23]
I'm not sure if this is user error or a weird quirk in the Census Bureau's API.

**Steps to reproduce:**
``conn = cenpy.base.Connection('ITMonthlyExportsStateHS')``
``df = conn.query(['STATE', 'ALL_VAL_MO'], time='from+2001-01')``
``HTTPError: 500 Server Error: Internal Server Error for url: https://api.census.gov/data/timeseries/intltrade/exports/statehs?get=STATE,ALL_VAL_MO&for=us:00&time=from+2001-01``

**Possible explaination:**
The ``query()`` method takes default values (``cols=[]``, ``geo_unit='us:00'``, ``geo_filter={}``, and ``api_key=''``), and I imagine there's a vast number of Census Bureau API calls that require a specified ``geo_unit``, but the call above does not (here's the [correct url](https://api.census.gov/data/timeseries/intltrade/exports/statehs?get=STATE,ALL_VAL_MO&time=from+2001-01), without the ``geo_unit`` parameter specified). 

Also, lines 137-147 in cenpy/remote.py seem a bit odd to me, although maybe it's due to something I don't understand. In line 137, the string method ``replace`` is called on ``geo_unit``, which would fail if ``geo_unit`` isn't a type ``str``. Then in 144 the code checks to see if ``geo_unit`` is a dict (which it couldn't be), and if not, it performs line 137 again. 

**Workaround:**
Explicitly specify ``geo_unit=''`` in the call:
``df = conn.query(['STATE', 'ALL_VAL_MO'], geo_unit='', time='from+2001-01')``

**Conclusion:**
Seems the dictionary portion is left-over from a previous version of the library that allowed dictionary values for ``geo_unit`` or possibly some future feature? @ljwolf Do you prefer the query method to have the default ``geo_unit`` value even if it results in mal-formed URLs when not required? I don't mind doing a pull request if there's interest.

Thanks again for such a useful tool!

**Comment by ljwolf** [comment]
Yeah, that `isinstance(geo_unit, dict)` never activates. Probably left over from when the API required dicts for those inputs. good catch. 

I'd hoped the `query` could be general enough to attach to all the census products, but this would be a good case where assuming `'us:00'` makes the common services work (ACS, decennial), but making it '' would fail. 

I think the "right" way to handle this is to check if the geo_unit specifier is required by looking in the `conn.variables.required` table, and if it is reqiured, set it correctly to `us:00`, and if it's not (or isn't even present), set to `''` or avoid adding to the query string altogether.

**Comment by ljwolf** [comment]
Always :smile:

**Comment by geoffrey-eisenbarth** [comment]
Heyo, @ljwolf  

Sorry for the (extended) delay. I was forced to work on other parts of my project that don't involve the USCB API for awhile, but looks like I'll be getting back to Census Bureau data soon. I'll try to get you a pull-request soon.

**Comment by ljwolf** [comment]
sounds good. let me know if I can provide any specific assistance!
