### ISSUE TITLE
FutureWarning in remote.py

### ISSUE THREAD

**Issue by geoffrey-eisenbarth** [ljwolf/cenpy#25]
``pd.DataFrame.convert_objects()`` has been depreciated in Pandas since 0.21.0, and raises a warning each time ``query()`` is called. Usually this wouldn't bother me too much, but I found an instance where it leads to mis-represented data.

When using Cenpy to fetch County Business Patterns, we use a call such as

``conn = cenpy.base.Connection('CBP2004')``
``df = conn.query(cols=['ESTAB', 'NAICS2002'], geo_unit='state:48', geo_filter={})``

For some reason, ``convert_objects()`` is deciding that the NAICS2002 column should be a float, and thus replaces NAICS codes such as '31-33', '44-45' with ``np.nan``.

Removing the line fixed both the warning and the issue with NAICS conversion. @ljwolf: are you familiar with situations in which the call to ``convert_objects()`` is beneficial?

EDIT: I see that not calling ``convert_objects`` will result in some numerical columns being returned as object dtypes. Is there a way to determine which columns of a given query actually represent numerical data? Maybe ``pd.to_numeric`` with ``errors='ignore'``?

**Comment by ljwolf** [comment]
Good idea; I think this would be good to merge. I knew `convert_objects` was being deprecated, but I hadn't earmarked the right version it was being removed. 

I'll look into this while I'm building on #27

**Comment by ljwolf** [comment]
This should be addressed in #28, and I'll make a new release sometime in the next month.
