### ISSUE TITLE
New datasets not available

### ISSUE THREAD

**Issue by aksa111** [ljwolf/cenpy#26]
Trying to do some analysis with a new dataset for 2016.  But, it seems to be not available using cenpy.  
`dataset = 'ACSSF5Y2016'
cen.explorer.explain(dataset)
`
returns

`KeyError: 'ACSSF5Y2016'`

Same code works with ACSSF5Y2015
Do you have any plans to update the dataset list soon?

**Comment by ljwolf** [comment]
This package creates the list of available endpoints automatically when it is imported. All current api endpoints exposed at [api.census.gov](https://api.census.gov/data.json) are discovered at import time and wrapped. Nothing is cached, so I can't import anything. 

If you look for yourself, you'll see that there's no `ACSSF5Y2016` resource. exposed *via* the main census API. `cenpy` can't wrap what it can't see at `api.census.gov`.

**Comment by dfolch** [comment]
If you’re looking for 2012-2016 ACS try `ACSDT5Y2016`.

**Comment by ljwolf** [comment]
Ahh, nice, that's the detailed table version? Maybe it'd help to add a better `explorer.available` format that searches the request for more metadata and stuff it into a table.
