### ISSUE TITLE
Possible to get down to block level?

### ISSUE THREAD

**Issue by wtadler** [ljwolf/cenpy#34]
Is it possible to use cenpy to get data from the Census API down to the block level?

Thanks!

**Comment by knaaptime** [comment]
it's certainly possible, but it depends on the survey and variable you need. In general I think ACS data are only published to blockgroup, not block. But if you need decennial data, you could do e.g.

```python
import cenpy
dec = cenpy.base.Connection('DecennialSF12010')
dec.query(cols=['H0010001'], geo_unit='block', geo_filter{'state':'11', 'county':'001'})
```

which would return housing units in the first county of DC. The census API forces you to specify a state and county when grabbing extracts for smaller geographies like blocks, so cenpy gives you convenience functions (`cenpy.tools.state_to_block` & `cenpy.tools.national_to_block`) for larger extracts

**Comment by wtadler** [comment]
Excellent, thanks so much!
