### ISSUE TITLE
Have Census API names changed? Might need to update documentation

### ISSUE THREAD

**Issue by wtadler** [ljwolf/cenpy#37]
Unless I'm missing something, the CenPy [documentation](https://github.com/ljwolf/cenpy/blob/master/README.rst) and [example](https://nbviewer.jupyter.org/github/ljwolf/cenpy/blob/master/demo.ipynb) [notebooks](https://gist.github.com/dfolch/2440ba28c2ddf5192ad7) might need updating, because none of the example API names (e.g., `2010sf1`, `2011acs5`, `2010acs5`, `ACSSF5Y2012`, `ACSSF5Y2013`) work.

[Seems like](https://api.census.gov/data.json) the main SF1 dataset is now called `DECENNIALSF12010`.

Relatedly, this gives you a useful table for seeing the available datasets:
```python
import urllib.request, json, pandas
with urllib.request.urlopen("https://api.census.gov/data.json") as url:
    data = json.loads(url.read().decode())
df = pandas.DataFrame(data['dataset'])
df['id'] = df['identifier'].apply(lambda x: x.split('id')[-1].lstrip('/'))
df = df.set_index('id').sort_index()
```

**Comment by loganpowell** [comment]
@wtadler as you've noticed, Census has changed a number of their endpoints. We apologize for the inconvenience this has caused you. `cenpy` is a library that helps a lot of people and we know that maintaining even a stable API over time is difficult, far more when the source changes the ontology. Please bear with us.

**Comment by knaaptime** [comment]
you should also be able to use `cenpy.explorer.available()` to list all the available endpoints

**Comment by ljwolf** [comment]
Thanks for the note @wtadler I'll try to get this done for `0.9.9`. 

I wanted the documentation to reflect a "standard" census product, but since the keys can change, I know they'll go out of date.

**Comment by ljwolf** [comment]
The documentation is updated.
