### ISSUE TITLE
handle missing values appropriately

### ISSUE THREAD

**Issue by knaaptime** [ljwolf/cenpy#41]
need to ensure we're handling [missing values](https://www.census.gov/data/developers/data-sets/acs-1year/notes-on-acs-estimate-and-annotation-values.html) appropriately

**Comment by ljwolf** [comment]
I believe this is addressed in #50, but I'm leaving this open to confirm its resolution for release.

**Comment by ljwolf** [comment]
This was fixed in #50 so far as I can tell. There are some dissatisfactions with this solution, however, since the various missing values represent different *kinds* of missingness. I think the way to handle this is to provide a `replace_missing=True` option.

**Comment by ljwolf** [comment]
this has now been implemented in the product feature branch.
