### ISSUE TITLE
cenpy v1.0.0 available via GitHub?

### ISSUE THREAD

**Issue by jGaboardi** [ljwolf/cenpy#48]
Awesome work and great [`gist`](https://nbviewer.jupyter.org/gist/ljwolf/3481aeadf1b0fbb46b72553a08bfc4e6?flush_cache=true) demonstrating the next release (and pre-release) of `cenpy`. Will the pre-release version be available via GitHub prior to the planned full release in July? I could not find a branch for it.

**Comment by knaaptime** [comment]
New api is in the product branch and there’s a prerelease on pypi

**Comment by jGaboardi** [comment]
ah! My oversight! Thanks @knaaptime!
