### ISSUE TITLE
Error when fetching Detroit, MI

### ISSUE THREAD

**Issue by stuartlynn** [ljwolf/cenpy#52]
When using the most recent version (new API (which is awesome btw)) trying to get 'Detroit, MI' with the command 

``` 
acs_2017 = products.ACS(2017)
acs_2017.from_place('Detroit, MI',[],level='tract')
```
I get an error 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-45-08a3e0e9ed55> in <module>()
      1 acs_2017 = products.ACS(2017)
----> 2 acs_2017.from_place('Detroit, MI',[],level='tract')

/opt/conda/lib/python3.6/site-packages/cenpy/products.py in from_place(self, place, variables, level, strict_within, return_bounds)
    386                                   .from_place(place, variables=variables, level=level,
    387                                               strict_within=strict_within,
--> 388                                               return_bounds=return_bounds)
    389         variables['GEOID'] = variables.GEO_ID.str.split('US').apply(lambda x: x[1])
    390         return_table = geoms[['GEOID', 'geometry']]\

/opt/conda/lib/python3.6/site-packages/cenpy/products.py in from_place(self, place, variables, level, geometry_precision, strict_within, return_bounds)
     84         name, state = place.split(',')
     85         place_ix, placematch = _fuzzy_match(name.strip(),
---> 86                                 _places.query('STATE == "{}"'.format(state.strip()))
     87                                        .TARGETNAME)
     88         placerow = _places.loc[place_ix]

/opt/conda/lib/python3.6/site-packages/cenpy/products.py in _fuzzy_match(matchtarget, matchlist)
    413     if len(split) == 1:
    414         if (table.score == table.score.max()).sum() > 1:
--> 415             ixmax, rowmax = _break_ties(matchtarget, table)
    416         else:
    417             ixmax = table.score.idxmax()

/opt/conda/lib/python3.6/site-packages/cenpy/products.py in _break_ties(matchtarget, table)
    455         ixmax_row = double_winners.loc[ixmax]
    456         warn('Cannot disambiguate placename {}. Picking the shortest, best '
--> 457              'matched placename, {}, from {}'.format(matchtarget, ixmax_row.target.item(),
    458                                                      ', '.join(double_winners.target.tolist())))
    459         return ixmax, ixmax_row

AttributeError: 'str' object has no attribute 'item'
```

Looks like `row.target` is a string rather than an object as expected here. Happy to look in to a fix and submit a PR

**Comment by stuartlynn** [comment]
Which branch is the --pre release / new API being developed on? Is it products?

**Comment by ljwolf** [comment]
Yes, the products branch!

This should be fixable by removing the "item()" call! Not sure why that
slipped through!

**Comment by stuartlynn** [comment]
Cool. Easy enough. Will implement and test and send a PR

**Comment by stuartlynn** [comment]
Hey so digging in to this a little more. I think the issue is that the fuzzy match for 'Detroit, MI' is coming back with the placerow: 
```
STATE                         MI
STATEFP                       26
TYPE          County Subdivision
TARGETFP                   22000
TARGETNAME          Detroit city
```
Which then seems to fail on the API call. This is despite their being an entry in the dataset for an Incorporated Place 

```
STATE                         MI
STATEFP                       26
TYPE          Incorporated Place
TARGETFP                   22000
TARGETNAME          Detroit city
```
The fuzzy match just happens to hit the County Subdivision before it hits the Incorporated Place. I propose we add an optional  `place_type` argument to the `from_place` function call that pre-filters the options before the fuzzy match happens. If `place_type` is not specified, we leave the function as it was before?

Let me know if that sounds good and I can implement and send a PR

**Comment by stuartlynn** [comment]
Yeah and sorry about the error in the title

**Comment by ljwolf** [comment]
> Yeah and sorry about the error in the title
No worries :smile: totally didn't notice til right now. 

> Let me know if that sounds good...

it does! My first reaction was that county subdivisions shouldn't be in the plcae list. But, having done some reading on the [County Subdivisions](https://www2.census.gov/geo/pdfs/reference/GARM/Ch8GARM.pdf), it does make sense that county subdivisions are in that placelist. 

I'm OK with that for sure. If you can send that, I'll merge it. 

For the release, I also think it might make sense to select the "biggest" place first. So, always pick an Incorporated place before a designated place, and then pick the county subdivision.

**Comment by stuartlynn** [comment]
That makes sense to me. So the order would be 

Incorporated Place
Census Designated Place
County Subdivision

?

**Comment by ljwolf** [comment]
Yeah, I think that makes sense for the most common set of queries. 

CDPs are pretty small... I'd need to do some checking about which might be more common, but I think that like... a named "place", even if it's by the census bureau, will be more common than what I'm seeing in the county subdivision tables.

**Comment by stuartlynn** [comment]
Cool. Ok will close out this issue and open another for the ordering.

**Comment by stuartlynn** [comment]
I guess the other issue here is that the API call when trying to access 
```
STATE                         MI
STATEFP                       26
TYPE          County Subdivision
TARGETFP                   22000
TARGETNAME          Detroit city
```
should work but that API call fails. 

I think this is because in the case of  County Subdivision the PLACE query variable is wrong and should be COUSUB . So we need some logic here: 

https://github.com/ljwolf/cenpy/blob/product/cenpy/products.py#L119

to switch between the appropriate query variable name.

An example query would look like this:

https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/tigerWMS_ACS2017/MapServer/20/query?where=STATE%3D26+AND+COUSUB%3D22000&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=&returnExtentsOnly=false&datumTransformation=&parameterValues=&rangeValues=&f=html

**Comment by ljwolf** [comment]
OK, That's definitely doable, I think. just another branch on that for the county subdivision type.
