### ISSUE TITLE
`variables` list modified in place

### ISSUE THREAD

**Issue by knaaptime** [ljwolf/cenpy#55]
in the product api, the variables list is being modified in place, which was causing me some trouble trying to iterate over a list of states and collect the same variables
![image](https://user-images.githubusercontent.com/4213368/58820394-5dd9b880-85e7-11e9-92c8-f5c1b86ad13b.png)

i solved by just passing copy of the list in each iteration, but thought this might be undesirable behavior

**Comment by ljwolf** [comment]
Yes! Definitely not desirable... I need to add a copy on input.

**Comment by knaaptime** [comment]
plain `product` is the current head for this branch, right? not any of the `product-*`

like any PRs should start from `product`, not `product-casesensitive` for example?

**Comment by ljwolf** [comment]
yes, the product branch is the head. Sorry for the vagueness. I've pruned
stale branches.

---
Levi John Wolf
Lecturer in Quantitative Human Geography | University of Bristol
Fellow | Center for Spatial Data Science, University of Chicago
Fellow | Alan Turing Institute for Data Science & Machine Learning
Director | Q-Step Program, University of Bristol
ljwolf.org

**Comment by ljwolf** [comment]
This is addressed in d8f255a0
