### ISSUE TITLE
docstring inconsistency in `Product.from_state`

### ISSUE THREAD

**Issue by knaaptime** [ljwolf/cenpy#56]
the first argument to `from_state` is `name`, but the docstring lists `state`. Do you have a preference for which should remain?
![image](https://user-images.githubusercontent.com/4213368/58825884-3d642b00-85f4-11e9-8efd-e09c1140f3ec.png)

**Comment by ljwolf** [comment]
`state` should be in the docstring, following `from_place`, `from_msa`, `from_csa`, etc. 

Also, `state,state` is wrong, and should be removed? I'm automatically editing that docstring, so maybe my automatic word replacement isn't doing the right thing :smile:

**Comment by ljwolf** [comment]
resolved by #69
